# SOLVENTS

WATER = 'water'
METHANOL = 1
ETHANOL = 2
DMSO = 3
DCM = 4
ACETONE = 5

# DEFAULT PARAMETERS

DEFAULT_STIR_RPM = 400 # rpm
DEFAULT_MOVE_SPEED = 20 # mL/min
DEFAULT_ASPIRATION_SPEED = DEFAULT_MOVE_SPEED
DEFAULT_DISPENSE_SPEED = DEFAULT_MOVE_SPEED
DEFAULT_CLEAN_STIR_TIME = 60 # seconds
DEFAULT_PUMP_PRIME_VOLUME = 3 # mL
DEFAULT_CLEAN_TUBING_VOLUME = 2.5 # mL
DEFAULT_CLEAN_TUBING_SOLVENT = WATER
DEFAULT_WASH_QUANTITY = 20
DEFAULT_DRY_TIME = 60
DEFAULT_FILTER_TIME = 60

# COMPONENTS

ROUND_BOTTOM_FLASK = 'Round Bottom Flask'

# MISC

ROOM_TEMPERATURE = 25

VOLUME_ML_UNIT_WORDS = ('ml', 'millilitres', 'milliliters', 'cc')
VOLUME_L_UNIT_WORDS = ('l', 'litres', 'liters')
VOLUME_DL_UNIT_WORDS = ('dl', 'decilitres', 'deciliters')
VOLUME_CL_UNIT_WORDS = ('cl', 'centilitres', 'centiliters')

